import type { LanguageCode } from './i18n';

const translations: Record<LanguageCode, Record<string, string>> = {
  en: { action: 'Consolidate', title: 'Consolidate funds', explanation: 'Prepare the minimum number of transactions needed to regroup confirmed outputs on your main address.', cancel: 'Cancel', prepare: 'Prepare', review: 'Consolidation ready', transactions: 'Transactions', inputs: 'Outputs to consolidate', fees: 'Total fees', send: 'Confirm and send all', loadingPrepare: 'Preparing consolidation...', loadingSend: 'Sending consolidation...', successTitle: 'Consolidation sent', successBody: 'All consolidation transactions were broadcast.', partialTitle: 'Partially sent', partialBody: 'Some transactions were sent. The remaining transactions are still ready.', unavailable: 'At least two confirmed outputs are required.' },
  zh: { action: '合并', title: '合并资金', explanation: '准备尽可能少的交易，将已确认的输出合并到您的主地址。', cancel: '取消', prepare: '准备', review: '合并已准备', transactions: '交易数', inputs: '待合并输出', fees: '总手续费', send: '确认并全部发送', loadingPrepare: '正在准备合并...', loadingSend: '正在发送合并...', successTitle: '合并已发送', successBody: '所有合并交易均已广播。', partialTitle: '部分已发送', partialBody: '部分交易已发送，其余交易仍可发送。', unavailable: '至少需要两个已确认的输出。' },
  hi: { action: 'समेकित करें', title: 'धन समेकित करें', explanation: 'पुष्टि किए गए आउटपुट को मुख्य पते पर जोड़ने के लिए न्यूनतम लेनदेन तैयार करें।', cancel: 'रद्द करें', prepare: 'तैयार करें', review: 'समेकन तैयार', transactions: 'लेनदेन', inputs: 'समेकित आउटपुट', fees: 'कुल शुल्क', send: 'पुष्टि करें और सभी भेजें', loadingPrepare: 'समेकन तैयार हो रहा है...', loadingSend: 'समेकन भेजा जा रहा है...', successTitle: 'समेकन भेजा गया', successBody: 'सभी समेकन लेनदेन प्रसारित किए गए।', partialTitle: 'आंशिक रूप से भेजा गया', partialBody: 'कुछ लेनदेन भेजे गए। शेष अभी तैयार हैं।', unavailable: 'कम से कम दो पुष्टि किए गए आउटपुट आवश्यक हैं।' },
  es: { action: 'Consolidar', title: 'Consolidar fondos', explanation: 'Prepara el mínimo de transacciones para agrupar las salidas confirmadas en tu dirección principal.', cancel: 'Cancelar', prepare: 'Preparar', review: 'Consolidación lista', transactions: 'Transacciones', inputs: 'Salidas a consolidar', fees: 'Comisiones totales', send: 'Confirmar y enviar todo', loadingPrepare: 'Preparando consolidación...', loadingSend: 'Enviando consolidación...', successTitle: 'Consolidación enviada', successBody: 'Todas las transacciones de consolidación fueron difundidas.', partialTitle: 'Envío parcial', partialBody: 'Algunas transacciones fueron enviadas. Las restantes siguen listas.', unavailable: 'Se requieren al menos dos salidas confirmadas.' },
  fr: { action: 'Consolider', title: 'Consolider les fonds', explanation: 'Prépare le minimum de transactions nécessaire pour regrouper les sorties confirmées sur votre adresse principale.', cancel: 'Annuler', prepare: 'Préparer', review: 'Consolidation prête', transactions: 'Transactions', inputs: 'Sorties à consolider', fees: 'Frais totaux', send: 'Confirmer et tout envoyer', loadingPrepare: 'Préparation de la consolidation...', loadingSend: 'Envoi de la consolidation...', successTitle: 'Consolidation envoyée', successBody: 'Toutes les transactions de consolidation ont été diffusées.', partialTitle: 'Envoi partiel', partialBody: 'Certaines transactions ont été envoyées. Les autres restent prêtes.', unavailable: 'Au moins deux sorties confirmées sont nécessaires.' },
  ar: { action: 'دمج', title: 'دمج الأموال', explanation: 'تحضير أقل عدد من المعاملات لدمج المخرجات المؤكدة في عنوانك الرئيسي.', cancel: 'إلغاء', prepare: 'تحضير', review: 'الدمج جاهز', transactions: 'المعاملات', inputs: 'المخرجات المراد دمجها', fees: 'إجمالي الرسوم', send: 'تأكيد وإرسال الكل', loadingPrepare: 'جارٍ تحضير الدمج...', loadingSend: 'جارٍ إرسال الدمج...', successTitle: 'تم إرسال الدمج', successBody: 'تم بث جميع معاملات الدمج.', partialTitle: 'تم الإرسال جزئيًا', partialBody: 'تم إرسال بعض المعاملات وما زال الباقي جاهزًا.', unavailable: 'يلزم مخرجان مؤكدان على الأقل.' },
  bn: { action: 'একত্র করুন', title: 'তহবিল একত্র করুন', explanation: 'নিশ্চিত আউটপুটগুলো প্রধান ঠিকানায় একত্র করতে সর্বনিম্ন সংখ্যক লেনদেন প্রস্তুত করুন।', cancel: 'বাতিল', prepare: 'প্রস্তুত', review: 'একত্রীকরণ প্রস্তুত', transactions: 'লেনদেন', inputs: 'একত্র করার আউটপুট', fees: 'মোট ফি', send: 'নিশ্চিত করে সব পাঠান', loadingPrepare: 'একত্রীকরণ প্রস্তুত হচ্ছে...', loadingSend: 'একত্রীকরণ পাঠানো হচ্ছে...', successTitle: 'একত্রীকরণ পাঠানো হয়েছে', successBody: 'সব একত্রীকরণ লেনদেন সম্প্রচার করা হয়েছে।', partialTitle: 'আংশিক পাঠানো হয়েছে', partialBody: 'কিছু লেনদেন পাঠানো হয়েছে। বাকিগুলো প্রস্তুত আছে।', unavailable: 'কমপক্ষে দুটি নিশ্চিত আউটপুট প্রয়োজন।' },
  pt: { action: 'Consolidar', title: 'Consolidar fundos', explanation: 'Prepara o menor número de transações para reunir as saídas confirmadas no seu endereço principal.', cancel: 'Cancelar', prepare: 'Preparar', review: 'Consolidação pronta', transactions: 'Transações', inputs: 'Saídas a consolidar', fees: 'Taxas totais', send: 'Confirmar e enviar tudo', loadingPrepare: 'Preparando consolidação...', loadingSend: 'Enviando consolidação...', successTitle: 'Consolidação enviada', successBody: 'Todas as transações de consolidação foram transmitidas.', partialTitle: 'Envio parcial', partialBody: 'Algumas transações foram enviadas. As restantes continuam prontas.', unavailable: 'São necessárias pelo menos duas saídas confirmadas.' },
  ru: { action: 'Объединить', title: 'Объединить средства', explanation: 'Подготовить минимальное число транзакций для объединения подтвержденных выходов на основном адресе.', cancel: 'Отмена', prepare: 'Подготовить', review: 'Объединение готово', transactions: 'Транзакции', inputs: 'Выходы для объединения', fees: 'Общая комиссия', send: 'Подтвердить и отправить все', loadingPrepare: 'Подготовка объединения...', loadingSend: 'Отправка объединения...', successTitle: 'Объединение отправлено', successBody: 'Все транзакции объединения отправлены в сеть.', partialTitle: 'Отправлено частично', partialBody: 'Часть транзакций отправлена. Остальные по-прежнему готовы.', unavailable: 'Требуется не менее двух подтвержденных выходов.' },
};

export const makeConsolidationTranslator = (language: LanguageCode) => (key: string) =>
  translations[language]?.[key] ?? translations.en[key] ?? key;
